apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      appProtocol: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
      appProtocol: https
  selector:
    app: nginx-ingress
